exclude: ".venv|__pycache__|tests/dev/|tests/fixtures/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      # - id: trailing-whitespace
      #   args: [--markdown-linebreak-ext=md]
  # - repo: https://github.com/amureki/pre-commit-pgFormatter
  #   rev: v1.3.0  # Use the sha / tag you want to point at
  #   hooks:
  #     - id: pg_format
  #       args: [-b,-f1,-C,-U2,-k,-g,-w80, -W80]


ci:
    autoupdate_schedule: quarterly
    skip: []
    submodules: false
