exclude: ".venv|__pycache__|tests/dev/|tests/fixtures/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.1.2
    hooks:
      - id: sqlfluff-lint
        args:
          - "--dialect"
          - "postgres"
      - id: sqlfluff-fix
        args:
          - "--dialect"
          - "postgres"


ci:
    autoupdate_schedule: quarterly
    skip: []
    submodules: false
